-- Initial simplified schema for the Caesar game.
-- Supabase Auth provides users, so there is no local users table here.

create table if not exists public.game_levels (
  id bigint generated by default as identity primary key,
  name text not null,
  prize text not null,
  rank integer not null unique
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  value text not null,
  level_id bigint not null references public.game_levels (id) on delete cascade,
  points integer not null check (points > 0),
  true_answer text not null
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions (id) on delete cascade,
  value text not null
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  owner uuid not null references auth.users (id) on delete cascade,
  total_points integer not null default 0 check (total_points >= 0),
  achieved_level bigint references public.game_levels (id) on delete set null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  current_question_id bigint references public.questions (id) on delete set null
);

create table if not exists public.user_answers (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  question_id bigint not null references public.questions (id) on delete cascade,
  answer_id bigint not null references public.answers (id) on delete cascade,
  level bigint not null references public.game_levels (id) on delete restrict,
  points integer not null default 0 check (points >= 0),
  is_true boolean not null default false,
  unique (game_id, question_id)
);

create index if not exists questions_level_id_idx on public.questions (level_id);
create index if not exists answers_question_id_idx on public.answers (question_id);
create index if not exists games_owner_idx on public.games (owner);
create index if not exists games_current_question_id_idx on public.games (current_question_id);
create index if not exists user_answers_game_id_idx on public.user_answers (game_id);
create index if not exists user_answers_question_id_idx on public.user_answers (question_id);
create index if not exists user_answers_answer_id_idx on public.user_answers (answer_id);
